// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG61r5mD4z-SvnOnVWqr_7geieDweMvcM',
    appId: '1:583179827621:web:7fa2d6ca75a61083e7504c',
    messagingSenderId: '583179827621',
    projectId: 'audio-app-a604c',
    authDomain: 'audio-app-a604c.firebaseapp.com',
    storageBucket: 'audio-app-a604c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ_0-12wFK4OU3PM8t9861JANpsPD_JLY',
    appId: '1:583179827621:android:1e46575452c4f6f3e7504c',
    messagingSenderId: '583179827621',
    projectId: 'audio-app-a604c',
    storageBucket: 'audio-app-a604c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuT5I8icpKXYux1Eh0C2AYUVNcKqsQ2bs',
    appId: '1:583179827621:ios:b81af0cf132aff9fe7504c',
    messagingSenderId: '583179827621',
    projectId: 'audio-app-a604c',
    storageBucket: 'audio-app-a604c.firebasestorage.app',
    iosBundleId: 'com.example.projectMob',
  );
}
